# Change these first
owner: win11react # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Win11React
    url: http://win11.blueedge.me/
  - name: Docs Site
    url: https://win11docs.asylum-os.com/
  - name: PR Preview System
    url: https://github.com/features/actions
  - name: App Store site
    url: https://win.asylum-os.com/store/
  - name: Blue's Website
    url: https://blueedge.me/
  - name: Fire Server
    url: https://fire.asylum-os.com/
  - name: Update System
    url: https://update-server-win11.vercel.app/
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Win11react status
  introTitle: "**Win11React** by blueedge."
  introMessage: Win11react status
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
